apiVersion: v1
kind: Secret
metadata:
  name: crms-secrets
  namespace: default
type: Opaque
stringData:
  db.user: crms_user
  db.password: changeme-in-production
  jwt.secret: your-secret-key-change-in-production-min-256-bits
